- block:
    - name: Include prompts
      import_tasks: prompts.yml

    - name: Network configured
      gce_net:
        name: "algo-net-{{ server_name }}"
        fwname: "algo-net-{{ server_name }}-fw"
        allowed: "udp:500,4500,{{ wireguard_port }};tcp:22"
        state: "present"
        mode: auto
        src_range: 0.0.0.0/0
        service_account_email: "{{ service_account_email }}"
        credentials_file: "{{ credentials_file_path  }}"
        project_id: "{{ project_id }}"

    - name: "Creating a new instance..."
      gce:
        instance_names: "{{ server_name }}"
        zone: "{{ algo_region }}"
        machine_type: "{{ cloud_providers.gce.size }}"
        image: "{{ cloud_providers.gce.image }}"
        service_account_email: "{{ service_account_email }}"
        credentials_file: "{{ credentials_file_path }}"
        project_id: "{{ project_id }}"
        metadata: '{"ssh-keys":"ubuntu:{{ ssh_public_key_lookup }}"}'
        network: "algo-net-{{ server_name }}"
        tags:
          - "environment-algo"
      register: google_vm

    - set_fact:
        cloud_instance_ip: "{{ google_vm.instance_data[0].public_ip }}"
        ansible_ssh_user: ubuntu
  rescue:
    - debug: var=fail_hint
      tags: always
    - fail:
      tags: always
