- block:
    - name: Include prompts
      import_tasks: prompts.yml

    - name: Set the DigitalOcean Access Token fact
      set_fact:
        algo_do_token: "{{ do_token | default(_do_token.user_input) | default(lookup('env','DO_API_TOKEN'), true) }}"
        algo_do_region: "{{ do_region | default(_do_region.user_input) | default(lookup('env','DO_REGION'), true) }}"
        public_key: "{{ lookup('file', '{{ SSH_keys.public }}') }}"

    - block:
        - name: "Delete the existing Algo SSH keys"
          digital_ocean:
            state: absent
            command: ssh
            api_token: "{{ algo_do_token }}"
            name: "{{ SSH_keys.comment }}"
          register: ssh_keys
          until: ssh_keys.changed != true
          retries: 10
          delay: 1

      rescue:
        - name: Collect the fail error
          digital_ocean:
            state: absent
            command: ssh
            api_token: "{{ algo_do_token }}"
            name: "{{ SSH_keys.comment }}"
          register: ssh_keys
          ignore_errors: yes

        - debug: var=ssh_keys

        - fail:
            msg: "Please, ensure that your API token is not read-only."

    - name: "Upload the SSH key"
      digital_ocean:
        state: present
        command: ssh
        ssh_pub_key: "{{ public_key }}"
        api_token: "{{ algo_do_token }}"
        name: "{{ SSH_keys.comment }}"
      register: do_ssh_key

    - name: "Creating a droplet..."
      digital_ocean:
        state: present
        command: droplet
        name: "{{ algo_server_name }}"
        region_id: "{{ algo_do_region }}"
        size_id: "{{ cloud_providers.digitalocean.size }}"
        image_id: "{{ cloud_providers.digitalocean.image }}"
        ssh_key_ids: "{{ do_ssh_key.ssh_key.id }}"
        unique_name: yes
        api_token: "{{ algo_do_token }}"
        ipv6: yes
      register: do

    - name: Add the droplet to an inventory group
      add_host:
        name: "{{ do.droplet.ip_address }}"
        groups: vpn-host
        ansible_ssh_user: root
        ansible_python_interpreter: "/usr/bin/python2.7"
        ansible_ssh_private_key_file: "{{ SSH_keys.private }}"
        do_access_token: "{{ algo_do_token }}"
        do_droplet_id: "{{ do.droplet.id }}"
        cloud_provider: digitalocean

    - set_fact:
        cloud_instance_ip: "{{ do.droplet.ip_address }}"

    - name: Tag the droplet
      digital_ocean_tag:
        name: "Environment:Algo"
        resource_id: "{{ do.droplet.id }}"
        api_token: "{{ algo_do_token }}"
        state: present

    - block:
        - name: "Delete the new Algo SSH key"
          digital_ocean:
            state: absent
            command: ssh
            api_token: "{{ algo_do_token }}"
            name: "{{ SSH_keys.comment }}"
          register: ssh_keys
          until: ssh_keys.changed != true
          retries: 10
          delay: 1

      rescue:
        - name: Collect the fail error
          digital_ocean:
            state: absent
            command: ssh
            api_token: "{{ algo_do_token }}"
            name: "{{ SSH_keys.comment }}"
          register: ssh_keys
          ignore_errors: yes

        - debug: var=ssh_keys

        - fail:
            msg: "Please, ensure that your API token is not read-only."
  rescue:
    - debug: var=fail_hint
      tags: always
    - fail:
      tags: always
